### ISSUE TITLE
Cannot find module 'iojs'

### ISSUE THREAD

**Issue by theworkflow** [onmodulus/get-version#5]
Version: `get-version@1.1.2`

Command: `get-version --engine node /path/to/package.json`

Package.json:

```
{
  "name": "meteor-dev-bundle",
  "version": "0.0.0",
  "dependencies": {
    "fibers": "1.0.1",
    "underscore": "1.5.2",
    "source-map-support": "0.2.8",
    "semver": "4.1.0"
  },
  "devDependencies": {
    "eachline": "https://github.com/meteor/node-eachline/tarball/ff89722ff94e6b6a08652bf5f44c8fffea8a21da",
    "chalk": "0.5.1"
  },
  "engines": {
    "node": "0.10.33"
  },
  "main": "../../main.js",
  "scripts": {
    "start": "node ../../main"
  }
}
```

Error:

```
module.js:340
    throw err;
    ^

Error: Cannot find module 'iojs'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:289:25)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at /Users/Jeremiah/.nvm/versions/node/v4.2.4/lib/node_modules/get-version/lib/engines/index.js:15:21
    at Array.forEach (native)
    at Object.<anonymous> (/Users/Jeremiah/.nvm/versions/node/v4.2.4/lib/node_modules/get-version/lib/engines/index.js:7:21)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
```

**Comment by theworkflow** [comment]
It's not loading all the files within the directory. The reference to the directory seems to be off.
